### PR TITLE
storage/kubernetes: fix conflict error detection in TRP creation

### LINKED ISSUE #822: error resources: ID already exists.
Im running dex v2.2.2 on kubernetes, after a pod restarts, i see multiple lines of failed creating third party resources: ID already exists.

should this be an error? should it log it once and maybe as info? or is it standard that I go in after each restart and update the client-id?

### PR DESCRIPTION
**Pull request by ericchiang**
PR #815 fixed the Kubernetes storage implementation by correctly
returning storage.ErrAlreadyExists on POST conflicts. This caused a
regression in TPR creation (#822) when some, but not all, of the
resources already existed. E.g. for users upgrading from old
versions of dex.

Fixes #822

### CODE REVIEW

File: storage/kubernetes/storage.go [hunk 1]
```diff
@@ -108,27 +113,29 @@ func (c *Config) open(logger logrus.FieldLogger) (*client, error) {
...
+	ok = true
 	for _, r := range thirdPartyResources {
 		err := cli.postResource("extensions/v1beta1", "", "thirdpartyresources", r)
 		if err != nil {
-			if e, ok := err.(httpError); ok {
-				if e.StatusCode() == http.StatusConflict {
-					cli.logger.Errorf("third party resource already created %q", r.ObjectMeta.Name)
-					continue
-				}
+			if err == storage.ErrAlreadyExists {
```
Comment (rithujohn191) [inline storage/kubernetes/storage.go]: Do we want to have a similar check for storage.ErrNotFound and have a separate message for that too?

Comment (ericchiang) [inline storage/kubernetes/storage.go]: `storage.ErrNotFound` would mean that TPRs weren't enabled on the server. hmmm, maybe? Let me go add that.

**Comment by ericchiang** [comment]
@rithujohn191 updated the logging message.
