### PR TITLE
email/smtp: Fix type comparison error

### LINKED ISSUE #134: Compilation error
```bash
➜  /tmp  git clone https://github.com/coreos/dex && cd dex
Cloning into 'dex'...
remote: Counting objects: 1209, done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 1209 (delta 7), reused 0 (delta 0), pack-reused 1188
Receiving objects: 100% (1209/1209), 976.31 KiB | 992.00 KiB/s, done.
Resolving deltas: 100% (329/329), done.
Checking connectivity... done.

➜  dex git:(master) ./build
Turning migrations into ./db/migrations/assets.go
Compiling migrations into migrations.go
# github.com/coreos/dex/email
Godeps/_workspace/src/github.com/coreos/dex/email/smtp.go:60: cannot convert "" to type int
Godeps/_workspace/src/github.com/coreos/dex/email/smtp.go:60: invalid operation: smtpCfg.Port == "" (mismatched types int and string)

➜  dex git:(master) ✗ go version
go version go1.5.1 darwin/amd64
```

### PR DESCRIPTION
**Pull request by derekparker**
Fixes #134

### CODE REVIEW

File: email/smtp.go [hunk 1]
```diff
@@ -57,7 +57,7 @@ func (cfg *SmtpEmailerConfig) UnmarshalJSON(data []byte) error {
 	if smtpCfg.Host == "" {
 		return errors.New("must set SMTP host")
 	}
-	if smtpCfg.Port == "" {
+	if smtpCfg.Port == 0 {
```
Comment (joeatwork) [inline email/smtp.go]: How did this compile? Maybe it would be worth adding a test here? (Also, please ask @bobbyrullo to take a look)

Comment (derekparker) [inline email/smtp.go]: Didn't compile before, does now :).

**Comment by ecnahc515** [comment]
Whoops. Lgtm
