### PR TITLE
cmd, db: verify at least one secret is passed to --key-secrets

### LINKED ISSUE #130: panic: runtime error: index out of range
I'm trying to get a basic Dex system up and running by following the [getting started guide](https://github.com/coreos/dex/blob/master/Documentation/getting-started.md).

I'm running inside an ubuntu:14.04 container that I've installed Go 1.4.2 and Postgres 9.3 into.

After some futzing with psql authentication I have a dex_db created, and I've set up the credentials into the connection string `DEX_DB_URL=postgres://postgres:pa55Word@localhost/dex_db?sslmode=disable`

When I start the overlord I'm seeing:

```
INFO: Performed 7 db migrations
INFO: Binding to 127.0.0.1:5557...
panic: runtime error: index out of range

goroutine 8 [running]:
github.com/coreos/dex/db.(*PrivateKeySetRepo).Set(0xc20801fc60, 0x7f22dbd4e048, 0xc20800bc00, 0x0, 0x0)
        /root/dex/Godeps/_workspace/src/github.com/coreos/dex/db/key.go:134 +0x607
github.com/coreos/go-oidc/key.rotatePrivateKeys(0x7f22dbd4da90, 0xc20801fc60, 0xc208095f80, 0x2, 0xecd94c15d, 0x355417cd, 0xb7a6c0, 0x0, 0x0)
        /root/dex/Godeps/_workspace/src/github.com/coreos/go-oidc/key/rotate.go:164 +0x54b
github.com/coreos/go-oidc/key.func·001()
        /root/dex/Godeps/_workspace/src/github.com/coreos/go-oidc/key/rotate.go:102 +0x1cb
github.com/coreos/go-oidc/key.func·002()
        /root/dex/Godeps/_workspace/src/github.com/coreos/go-oidc/key/rotate.go:128 +0x232
created by github.com/coreos/go-oidc/key.(*PrivateKeyRotator).Run
        /root/dex/Godeps/_workspace/src/github.com/coreos/go-oidc/key/rotate.go:133 +0x19c

goroutine 1 [chan receive]:
main.main()
        /root/dex/Godeps/_workspace/src/github.com/coreos/dex/cmd/dex-overlord/main.go:142 +0x149b

goroutine 5 [chan receive]:
database/sql.(*DB).connectionOpener(0xc2080f1400)
        /usr/local/go/src/database/sql/sql.go:589 +0x4c
created by database/sql.Open
        /usr/local/go/src/database/sql/sql.go:452 +0x31c

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 6 [IO wait]:
net.(*pollDesc).Wait(0xc208010ae0, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208010ae0, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc208010a80, 0x0, 0x7f22dbd4ad48, 0xc20802bb68)
        /usr/local/go/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc208030110, 0x479aa4, 0x0, 0x0)
        /usr/local/go/src/net/tcpsock_posix.go:234 +0x4e
net/http.tcpKeepAliveListener.Accept(0xc208030110, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:1976 +0x4c
net/http.(*Server).Serve(0xc2080525a0, 0x7f22dbd4db98, 0xc208030110, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:1728 +0x92
net/http.(*Server).ListenAndServe(0xc2080525a0, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:1718 +0x154
main.func·001()
        /root/dex/Godeps/_workspace/src/github.com/coreos/dex/cmd/dex-overlord/main.go:138 +0x2a
created by main.main
        /root/dex/Godeps/_workspace/src/github.com/coreos/dex/cmd/dex-overlord/main.go:139 +0x1444

goroutine 7 [select]:
github.com/coreos/dex/db.func·002()
        /root/dex/Godeps/_workspace/src/github.com/coreos/dex/db/gc.go:59 +0x3db
created by github.com/coreos/dex/db.(*GarbageCollector).Run
        /root/dex/Godeps/_workspace/src/github.com/coreos/dex/db/gc.go:78 +0xfb
```

### PR DESCRIPTION
**Pull request by ericchiang**
Passing an empty list to the overlord's --key-secrets flag currently causes an out of range panic. Always check to ensure there's at least one element.

Fixes #130

### CODE REVIEW

File: db/key.go [hunk 1]
```diff
@@ -196,7 +202,3 @@ func (r *PrivateKeySetRepo) Get() (key.KeySet, error) {
 	}
 	return key.KeySet(pks), nil
 }
-
-func (r *PrivateKeySetRepo) active() []byte {
```
Comment (bcwaldon) [inline db/key.go]: I'd like to hear how @bobbyrullo had originally intended this function be used.

**Comment by bcwaldon** [comment]
LGTM but I want @bobbyrullo to look at this before it lands

**Comment by bobbyrullo** [comment]
I think the check should also exist within main so that you can specify what flag should be changed to fix it. 

The reason the `active` method was there was as much for documentation as anything else - to show that the active key is the one at index 0. It also insulates us in case we choose another method of marking things as active. I just don't like magic numbers, even if they are 0. So, I prefer not getting rid of it, but of course I'd say that as I wrote it.

**Comment by ericchiang** [comment]
@bobbyrullo I've gone ahead and added the `active` method back in (it now returns an error rather than panicing). In addition, both the dex-worker and dex-overloard return errors directly in the main.

**Comment by bobbyrullo** [comment]
LGTM
