### PR TITLE
storage: fix postgres timezone handling

### LINKED ISSUE #745: storage/sql: postgres doesn't perist timezone
Using the latest build and fresh postgres database as the storage backend, I was unable to login. 

```
Authorization request period has expired.
```

Digging a bit deeper I noticed that the table was using the __timestamp__ column type (w/o timezone). So it seemed to me that dex was losing some precision between the insert and the select. 

Also telling was the frequent key rotations
```
2016/12/13 14:43:36 keys expired, rotating
2016/12/13 14:43:36 keys rotated, next rotation: 2016-12-13 20:43:36.554887954 -0600 CST
2016/12/13 14:43:36 listening (http) on 0.0.0.0:5556
2016/12/13 14:44:06 keys expired, rotating
2016/12/13 14:44:06 keys rotated, next rotation: 2016-12-13 20:44:06.965425402 -0600 CST
2016/12/13 14:44:36 keys expired, rotating
2016/12/13 14:44:37 keys rotated, next rotation: 2016-12-13 20:44:37.116072981 -0600 CST
2016/12/13 14:45:07 keys expired, rotating
2016/12/13 14:45:07 keys rotated, next rotation: 2016-12-13 20:45:07.321215505 -0600 CST
2016/12/13 14:45:37 keys expired, rotating
2016/12/13 14:45:37 keys rotated, next rotation: 2016-12-13 20:45:37.567846803 -0600 CST
2016/12/13 14:46:07 keys expired, rotating
2016/12/13 14:46:07 keys rotated, next rotation: 2016-12-13 20:46:07.875356915 -0600 CST
2016/12/13 14:46:37 keys expired, rotating
2016/12/13 14:46:38 keys rotated, next rotation: 2016-12-13 20:46:38.063993965 -0600 CST
2016/12/13 14:47:08 keys expired, rotating
2016/12/13 14:47:08 keys rotated, next rotation: 2016-12-13 20:47:08.349067898 -0600 CST
2016/12/13 14:47:38 keys expired, rotating
2016/12/13 14:47:38 keys rotated, next rotation: 2016-12-13 20:47:38.889484596 -0600 CST
2016/12/13 14:48:08 keys expired, rotating
2016/12/13 14:48:09 keys rotated, next rotation: 2016-12-13 20:48:09.681262225 -0600 CST
```

Not sure if i missed something, but my resolution was to wrap the default server.now function with one that returns UTC.

### PR DESCRIPTION
**Pull request by ericchiang**
Dex's Postgres client currently uses the `timestamp` datatype for
storing times. This lops of timezones with no conversion, causing
times to lose locality information.

We could convert all times to UTC before storing them, but this is
a backward incompatible change for upgrades, since the new version
of dex would still be reading times from the database with no
locality.

Because of this intrinsic issue that current Postgres users don't
save any timezone data, we chose to treat any existing installation
as corrupted and change the datatype used for times to `timestamptz`.
This is a breaking change, but it seems hard to offer an
alternative that's both correct and backward compatible.

Additionally, an internal flag has been added to SQL flavors,
`supportsTimezones`. This allows us to handle SQLite3, which doesn't
support timezones, while still storing timezones in other flavors.
Flavors that don't support timezones are explicitly converted to
UTC.

Closes #745

cc @jwmaag @rithujohn191

### CODE REVIEW

**Comment by ericchiang** [comment]
Still need to test the Kubernetes storage.

**Comment by ericchiang** [comment]
Kubernetes storage passes the new conformance tests.

File: storage/sql/sql.go [hunk 1]
```diff
@@ -107,6 +113,19 @@ func (f flavor) translate(query string) string {
 	return query
 }
 
+func (c *conn) translateArgs(args []interface{}) []interface{} {
```
Comment (rithujohn191) [inline storage/sql/sql.go]: Could you please add a comment about what translateArgs does
