### PR TITLE
remove passwordInfos from local connector

### LINKED ISSUE #286: dex should only load password infos from local connector in --no-db mode
Error message:

```console
$ ./bin/dex-worker --db-url 'postgres://postgres@172.16.28.18/postgres?sslmode=disable'
WARN: Running with no limit on: database idle connections
WARN: Running with no limit on: database open connections
FATAL: Failed registering connector: error loading PasswordInfo[0]: "ID not available"
```

Steps to replicate

My bash_profile

```bash
export DEX_WORKER_CONNECTORS=$DEX/static/fixtures/connectors.json.sample
export DEX_WORKER_EMAIL_CFG=$DEX/static/fixtures/emailer.json.sample
export DEX_WORKER_EMAIL_TEMPLATES=$DEX/static/email
export DEX_WORKER_ENABLE_REGISTRATION=true
export DEX_WORKER_KEY_SECRETS="jqtjvAyPkOaT3yVn/c8T4tIbDuUGTm9uDh0Me7Gd+v4="
export DEX_OVERLORD_KEY_SECRETS=$DEX_WORKER_KEY_SECRETS
export DEX_OVERLORD_ADMIN_API_SECRET="7SuES8ZsvyC8Zbezp85FpqWyhvO3v7ySm0eB6IZUd5OfyWZWbM4XEybBfOJhHlOQMHmwYXu35nP39y7ppnRbV2BJExwwx7GdkbCAyjDSa82qN2OBlFKZiISNl0bo7Wof8yIPfwra+9/asnyO+wPhtXjnRgaHtCNL5mdjMV5U4dE="
```

1) Run postgres

```console
$ sudo rkt run --net=host quay.io/coreos/postgres
...
```

2) Run dex overlord

```console
$ ./bin/dex-overlord --db-url 'postgres://postgres@172.16.28.18/postgres?sslmode=disable'
INFO: Performed 10 db migrations
INFO: Binding to 127.0.0.1:5557...
```

3) Run dex worker

```console
$ ./bin/dex-worker --db-url 'postgres://postgres@172.16.28.18/postgres?sslmode=disable' --enable-client-registration=true
WARN: Running with no limit on: database idle connections
WARN: Running with no limit on: database open connections
ERROR: No connectors, will wait. Retrying in 1s.
ERROR: No connectors, will wait. Retrying in 2s.
ERROR: No connectors, will wait. Retrying in 4s.
ERROR: No connectors, will wait. Retrying in 8s.
ERROR: No connectors, will wait. Retrying in 8s.
```

4) Set connectors

```console
$ ./bin/dexctl set-connector-configs --db-url 'postgres://postgres@172.16.28.18/postgres?sslmode=disable' static/fixtures/connectors.json.sample 
Saved 4 connector config(s)
$ cat static/fixtures/connectors.json.sample 
[
	{
		"type": "local",
		"id": "local",
		"passwordInfos": [
			{
				"userId":"elroy-id",
				"passwordPlaintext": "bones"
			},
			{
				"userId":"penny",
				"passwordPlaintext": "kibble"
			}
		]
	},
	{
		"type": "oidc",
		"id": "google",
		"issuerURL": "https://accounts.google.com",
		"clientID": "${CLIENT_ID}",
		"clientSecret": "${CLIENT_SECRET}"
	},
	{
		"type": "github",
		"id": "github",
		"clientID": "${CLIENT_ID}",
		"clientSecret": "${CLIENT_SECRET}"
	},
	{
		"type": "bitbucket",
		"id": "bitbucket",
		"clientID": "${CLIENT_ID}",
		"clientSecret": "${CLIENT_SECRET}"
	}
]
```

5) Try to restart worker

```console
ERROR: No connectors, will wait. Retrying in 8s.
INFO: Loaded IdP connector: id=local type=local
INFO: Loaded IdP connector: id=google type=oidc
INFO: Loaded IdP connector: id=github type=github
INFO: Loaded IdP connector: id=bitbucket type=bitbucket
INFO: Binding to 127.0.0.1:5556...
^C
$ ./bin/dex-worker --db-url 'postgres://postgres@172.16.28.18/postgres?sslmode=disable'
WARN: Running with no limit on: database idle connections
WARN: Running with no limit on: database open connections
FATAL: Failed registering connector: error loading PasswordInfo[0]: "ID not available"
```

### LINKED ISSUE #340: Better specification of password info in --no-db mode
It's really weird that user passwords are specified in the connectors.json. It's also only valid for --no-db mode and will cause panics with Postgres (#286).

For instance, our example connector JSON file looks like this:

```json
[
	{
		"type": "local",
		"id": "local",
		"passwordInfos": [
			{
				"userId":"elroy-id",
				"passwordPlaintext": "bones"
			},
			{
				"userId":"penny",
				"passwordPlaintext": "kibble"
			}
		]
	}
]
```

Move these out of the connector and put them in the users.json file.

```json
[
    {
        "user":{
            "id": "elroy-id",
            "email": "elroy77@example.com",
            "displayName": "Elroy Jonez",
            "passwordPlaintext": "bones"
        },
        "remoteIdentities": [
            {
                "connectorId": "local",
                "id": "elroy-id"
            }
        ]
    }
]
```

Since this file is only parsed for --no-db mode, it seems reasonable to put that data there.

### PR DESCRIPTION
**Pull request by ericchiang**
In --no-db mode, load passwords from the users file instead of the
connectors file. This allows us to remove the password infos field
from the local connector and stop loading them during connector
registration, a case that was causing panics when using a real
database (see #286).

Fixes #286
Closes #340

### CODE REVIEW

**Comment by ericchiang** [comment]
Note that this has no impact on dex other than --no-db mode which we do not guarantee backwards compatibility for.

Using the `PasswordInfos` field on the local connector during full installations would result in panics as soon as a worker connected to the database after the initial connection (a second worker or the initial worker restarting). So this only prevents uses that would already result in cashes.

File: server/config.go [hunk 1]
```diff
@@ -163,13 +166,38 @@ func (cfg *SingleServerConfig) Configure(srv *Server) error {
 	return nil
 }
 
-func loadUsers(filepath string) (users []user.UserWithRemoteIdentities, err error) {
+// loadUsers parses the user.json file and returns the users to be created.
+func loadUsers(filepath string) (users []user.UserWithRemoteIdentities, pwis []user.PasswordInfo, err error) {
```
Comment (bobbyrullo) [inline server/config.go]: Stuff like this is much easier to test if you separate out the concept of loading from a file from reading from a reader. In other words, there should be a loadUsersFromReader method which does most of the heavy lifting here, and then you dont have to do this tempfile stuff in tests. See for example NewEmailerConfigFromReader

**Comment by bobbyrullo** [comment]
just one comment.

**Comment by ericchiang** [comment]
:+1: updated

File: server/config.go [hunk 2]
```diff
@@ -167,20 +168,23 @@ func (cfg *SingleServerConfig) Configure(srv *Server) error {
...
+func loadUsers(filepath string) ([]user.UserWithRemoteIdentities, []user.PasswordInfo, error) {
 	f, err := os.Open(filepath)
 	if err != nil {
 		return nil, nil, err
 	}
 	defer f.Close()
+	return readUsers(f)
+}
 
+func readUsers(r io.Reader) (users []user.UserWithRemoteIdentities, pwis []user.PasswordInfo, err error) {
```
Comment (bobbyrullo) [inline server/config.go]: nit: convention here, and in other places is loadXXXFromReader

**Comment by bobbyrullo** [comment]
naming nit, otherwise LGTM

File: server/config.go (hunk 2 above)
Comment (ericchiang) [inline server/config.go]: force pushing to update this

**Comment by ericchiang** [comment]
@bobbyrullo going to squash and merge if that's cool with you

**Comment by bobbyrullo** [comment]
Yes please
